# Generated by Django 6.0.7 on 2026-07-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='interest',
            index=models.Index(fields=['staff_profile', 'name'], name='interest_owner_name_idx'),
        ),
        migrations.AddIndex(
            model_name='projectidea',
            index=models.Index(fields=['staff_profile', 'title'], name='project_owner_title_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name', 'email'], name='user_display_order_idx'),
        ),
    ]
